export enum YuSortPlaylistTypes {
    BY_SONG_ARTIST_AND_TITLE_ASC = "BY_SONG_ARTIST_AND_TITLE_ASC",
    BY_SONG_ARTIST_AND_TITLE_DESC = "BY_SONG_ARTIST_AND_TITLE_DESC",
    BY_SONG_LENGTH_ASC = "BY_SONG_LENGTH_ASC",
    BY_SONG_LENGTH_DESC = "BY_SONG_LENGTH_DESC",
    BY_SONG_TITLE_ASC = "BY_SONG_TITLE_ASC",
    BY_SONG_TITLE_DESC = "BY_SONG_TITLE_DESC"
}